version: "3.9"

services:
  #Database
  app-db:
    image: postgres
    container_name: apollo-db
    environment:
      POSTGRES_DB: "graphql-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_ROOT_PASSWORD: "password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d graphql-db -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - app-db-volume:/var/lib/mysql

  #Api service
  api-service:
    container_name: apollo-service-container
    build:
      dockerfile: ./Dockerfile
    image: abeldlp/graphql-api-service
    ports:
      - "8080:8080"
    depends_on:
      app-db:
        condition: service_healthy

volumes:
  app-db-volume:
